AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'bin/{rails,rake}'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/


  
Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/LineLength:
  Max: 250
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Style/SymbolArray:
  Enabled: false
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

