require: 
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'shared/**/*'
    - 'storage/**/*'
    - 'vendor/**/*'
    - '*.js.erb'
  NewCops: enable
  SuggestExtensions: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/LineLength:
  Max: 200
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact
Layout/TrailingEmptyLines:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Style/SymbolArray:
  Enabled: false
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 200

Rails/SkipsModelValidations:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false

Performance/Caller:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false