language: ruby
rvm:
- 2.6.5
addons:
  postgresql: "12.1"
  apt:
  packages:
  - postgresql-12
  - postgresql-client-12
env:
  global:
  - PGPORT=5433
before_script:
- psql -c "CREATE DATABASE testing_db;" -U postgres
- psql -c "CREATE USER <%= Rails.application.credentials.psql[:user] %> WITH PASSWORD '<%= Rails.application.credentials.psql[:password] %>';" -U postgres
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop