language: ruby
rvm: 2.6.5
before_install:
  - sudo apt-get update
  - sudo apt-get -y remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo service postgresql restart 12
  - nvm install 12
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get install -y yarn=1.22.4-1
cache:
  yarn: true
before_script:
  - yarn install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rails webpacker:compile
script:
  - bundle exec rspec
  - bundle exec rubocop
services:
  - postgresql
addons:
  postgresql: "12.1"
env:
  global:
  - PGPORT=5433



  before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true