language: ruby
rvm: 2.7.2
env:
  - DB_USERNAME='cpcwood' DB_PASSWORD='password'
before_install:
  - echo $DB_USERNAME
  - echo $DB_PASSWORD
  - psql -c "CREATE USER $($DB_USERNAME) SUPERUSER LOGIN CREATEDB UNENCRYPTED PASSWORD $($DB_PASSWORD);" -U postgres
  - nvm install 14
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_script:
  - bundle install --without development
  - yarn install
  - bundle exec rails db:create db:migrate
  - bundle exec rails webpacker:compile
script:
  - bundle exec rspec
  - bundle exec rubocop -a -c ./.rubocop.yml
  - yarn test
  - yarn lint
services:
  - postgresql
repo_token:
  secure: "MseuIag5/s4xStZ672b/XX56sx1s2e2CtbRFkp4DMXlUbP4/JjRJrvQgBD6DgesULQFiSUifBMDMsKDY4B7yR3tH5eSNmH03K1guIKCAlGyYOsHcRjeER5HPKgjwRO630TKaKGU/f00JZ6IV3xNDsbCo1CaAq/LZkYlHbQqJALrHlleq/ZINr2oI1d+GcNHbCnBz5OLypm+RwbFJv1X33XctpRuAOBJJaXgxaYanweKd1JHioeAjMq/fmunwmzPtTOFB0ylQhw4B/3EUulRvIT73nCyJJLfGOab72JJoazSsqez13OlsVXQbqoQtoX1pYBytQbUoj3BskNmTcLTrXzn0RNRaWjWcl6ktu5vwGMYl/ql3gWYLI/WIHbE2tQ6sRP3F2+QMwWfbI6J+xDdZNyCBf8460VGnriMNEIp8drgIWabF+Z3DboJcP8Hp4MYk7IGUwY6g36ImfbW6jRHk2HO4A6trcxJXY4IPGwTKFlyYvcM1QVx7NV5+fw/Hr2K+QUQ1CJ6fYXyvsgWJFbTdHjCG3lmiZE5q7qAC4/KlyB8KxHVNLHeIKKehZxr79HL8xd1L38NOcVdetCdTTpLafhYFRviR5bPzJwuHJi46jr2yGy3+/3yBPltYt47DV/y/jBhUVIJRPFexy4l/c6RUJTPubL1sBoNaePK6bsz4/HU="