language: ruby
rvm: 2.7.2
env:
  global:
    - secure: "haAd+u+eApObQEJwW5LP5I0hx8QihSdiRuyHBd5F/obQRA8WToSG0iWKw0dwjjHAmfOUe+9SA8ZMXf+WYsf7L1qcYQwMFDMttl6vZ8hVzOY0beww9MUZ0Y/siu1T99+fAst4kmHeQ1aTZHUJn0U7CLB0yBjGjdhVi34DuyM5zD9OTFb1aJ514ApXVWTkVinOEcnsE4S1Up3fuGtU0Az+HsVBeTztwbJy8IT1FFbJ+jtQUlf+J4YSdBlpP2P7BfxaAc7KpLttBlCHMo6OJv20uueAu877sJAWoW+zO9pbatl309JDULPmEln+bmVzeE7qQ9PUw9pfL5TKJvXuZlyF1rBN4I+/ph3vACAWgsf09Tvgfcz+sMNSP6AZAR++60DIsmeNxWY9oIZHIm/lhTjXbW1IZBSXw+/nbPR/8ZUhBp1jW2wkX6KqJqNfatfK/yE8f9E32/O63/GQrd9GHPb8LbDmGg5E7J4Uu2KH3smwlz38Ppcs3rymH1ZjPUTRCIaH36SP7O1hlQR5L5vT+pTvhJHIe4/Z5RbSzWNWwMtqxo7+huAvwKbPm6k77mMF+orPdBB3c5IT16AW3Rc0l1i0n+ti2JaoFFStuNCCBOUxT/ZsJAoFQARWRTgJsygIZohYCP7R10DVs1EXRHPDTZS60KT2Z0y6ziQvBLZEusRbB7g="
    - secure: "PavtOFRrtq8WGlisLVltpYITQhcDT7i5YozGr95zlK5+etV25DCX+nvEneRkKJ+0AWvshxo7ighKvpylICfzYVUUYMo3YlE/34TuzFC6a/QHPkp38Nddj1Un8ljF6/DxgBbwdtpDip2JGp+5ElXnUxMgzFz2FtlRhXBO7gN4LlfPNnJmHvUQcbflD61YBhw9MIC/OIJXorB6lPlzYyd1XHXDwP7IhpXdf7g7MOUEmukZUCJnyvL0vVqndXG8xsAmm88mfBqLk271dPVHFagG/myCn4bxgoWSVL9V5eCQn9uvOpG8R7pX/88HflcVSTO0UEA8AE8of+nEICcT3NlRUM90kiCR/gt/np+i1qPULgYTg06bFC0GCr12+FgEMa1e88NRYdloBKK7dZCRMx/iYrY5Ira7pnHEKbtvk1klkOvemhDlH7uTHiVw4VZSHqEwR3/GuD6B/0aOBdwl/CC81C3QViCmm7OczoTPt/Av7mh3gxrBPAMhI/OX4mOc2bEPfi11maVa2Geyh5oYjny5TXU1sX9/+Evb+2wVPgDKkfPJT8ZHFjAYI4EUGJs0CdU6UUolBZGPu2dgeDF6iiEZZxtzaKU6RazbKJFv6ivYKsxlxplIX2quaPkKmZbWEaDkjkOSFWSOcYd8WogDBAsMbRte5lnbG/t1k7BD7uoDfks="
    - DB_USERNAME=cpcwood DB_PASSWORD=password DOCKER_IMAGE_NAME=cpcwood/home-server-app DOCKER_USERNAME=cpcwood 
services:
- postgresql
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_install:
  - psql -c "CREATE ROLE $DB_USERNAME SUPERUSER LOGIN CREATEDB UNENCRYPTED PASSWORD
    '$DB_PASSWORD';" -U postgres
  - nvm install 14
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
before_script:
  - bundle install --without development
  - yarn install
  - bundle exec rails db:create db:migrate
  - bundle exec rails webpacker:compile
script:
  - bundle exec rspec
  - bundle exec rubocop -a -c ./.rubocop.yml
  - yarn test
  - yarn lint
after_success:
  - ./scripts/travis-ci/travis-ci-merge-script.sh
deploy:
  provider: script
  script: bash ./scripts/travis-ci/travis-ci-docker-build-and-publish.sh
  on:
    branch: master