version: "3.7"

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: cpcwood
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - '5432:5432'
    volumes:
      - /var/db/psql/13:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server
    volumes:
      - /var/db/redis:/data

  sidekiq:
    image: cpcwood/home-server-worker
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
    env_file:
      - ./config/env/docker.env
    security_opt:
      - seccomp:"./config/chrome.json"

  web:
    image: cpcwood/home-server-app
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      - RAILS_ENV=production
    env_file:
      - ./config/env/docker.env
    ports:
      - '80:5000'