---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-server-app-deployment
  labels:
    cpcwood.com/name: home-server-app
    cpcwood.com/version: "1.0.0"
    cpcwood.com/component: application-server
    cpcwood.com/part-of: home-server
    cpcwood.com/managed-by: cpcwood
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 2
  selector:
    matchLabels:
      app: home-server-app
  template:
    metadata:
      labels:
        app: home-server-app
    spec:
      containers:
        - name: home-server-app
          image: cpcwood/home-server-app:CONTAINER_VERSION
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 4
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 4
          envFrom:
            - configMapRef:
                name: home-server-app-config


---
apiVersion: v1
kind: Service
metadata:
  name: home-server-app-service
spec:
  selector:
    app: home-server-app
  ports:
    - name: http-proxy
      protocol: TCP
      port: 5000
      targetPort: 5000

---