apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.global.externalSecretRefreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.global.clusterSecretStore }}
  target:
    name: {{ include "db.fullname" . }}-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: {{ .Values.global.secretPrefix }}/{{ .Values.externalSecrets.dbBundle }}
