---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-server-db-volume
  labels:
    type: db
spec:
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/home-server-pg-data # path to local data storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-name
              operator: In
              values:
                - <local-node-affinity-tag>

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-server-redis-volume
  labels:
    type: redis
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/home-server-redis-data # path to local data storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-name
              operator: In
              values:
                - <local-node-affinity-tag>

---

