version: 2.1

orbs:
  ruby: circleci/ruby@1.0 
  node: circleci/node@2
  coveralls: coveralls/coveralls@1.0.4

jobs:         
  test:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers 
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: cpcwood-circleci
          POSTGRES_PASSWORD: "test"
          POSTGRES_DB: home_server_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: cpcwood-circleci
      PGPASSWORD: "test"
      DB_NAME_TEST: home_server_test
      RAILS_ENV: test
    steps:
      - checkout 
      - ruby/install-deps 
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov/home-server.lcov

workflows:
  version: 2
  test_and_upload:
    jobs:
      - test