version: 2.1

orbs:
  ruby: circleci/ruby@1.0 
  node: circleci/node@2
  docker: circleci/docker@1.5.0
  kubernetes: circleci/kubernetes@0.11.2

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build_base:
          requires:
            - test
          filters:
             branches:
               only: master
      - build_app:
          requires:
            - build_base
          filters:
             branches:
               only: master
      - build_worker:
          requires:
            - build_base
          filters:
             branches:
               only: master
      - deploy:
          requires:
            - test
            - build_base
            - build_app
            - build_worker
          filters:
             branches:
               only: master

jobs:     
  test:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers 
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: cpcwood-circleci
          POSTGRES_PASSWORD: "test"
          POSTGRES_DB: home_server_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: cpcwood-circleci
      PGPASSWORD: "test"
      DB_NAME_TEST: home_server_test
      RAILS_ENV: test
    steps:
      - checkout 
      - ruby/install-deps 
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - run:
          name: Rubocop Linter
          command: bundle exec rubocop -a
      - run:
          name: JavaScript Testing
          command: yarn test
      - run: 
          name: JavaScript Linting
          command: yarn lint
      - run:
          name: Automerge PR
          command: |
            set +e
            ./scripts/circle-ci/circle-ci-auto-merge.sh
            if [ $? = 0 ]; then
                echo 'Merge successful'
            else
                echo 'No merge'
            fi
  build_base:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          keys:
            - home-server-base-v2-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/home-server-base.tar | true
      - run:
          name: Build application base Docker image
          command: |
            docker build \
              --cache-from=$DOCKER_USERNAME/home-server-base \
              -t "$DOCKER_USERNAME/home-server-base:$(echo $CIRCLE_SHA1 | head -c8)" \
              -t "$DOCKER_USERNAME/home-server-base:latest" \
              --build-arg grecaptcha_site_key=$GRECAPTCHA_SITE_KEY \
              -f ./base.Dockerfile \
              .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin >/dev/null 2>&1
            docker push $DOCKER_USERNAME/home-server-base
          background: true
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/home-server-base.tar $DOCKER_USERNAME/home-server-base
      - save_cache:
          key: home-server-base-v2-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/home-server-base.tar
  build_app:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          keys:
            - home-server-base-v2-{{ .Branch }}
            - home-server-app-v2-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/home-server-base.tar | true
            docker load -i /caches/home-server-app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --cache-from=$DOCKER_USERNAME/home-server-app \
              -t "$DOCKER_USERNAME/home-server-app:$(echo $CIRCLE_SHA1 | head -c8)" \
              -t "$DOCKER_USERNAME/home-server-app:latest" \
              .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin >/dev/null 2>&1
            docker push $DOCKER_USERNAME/home-server-app
          background: true
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/home-server-app.tar $DOCKER_USERNAME/home-server-app
      - save_cache:
          key: home-server-app-v2-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/home-server-app.tar
  build_worker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          keys:
            - home-server-base-v2-{{ .Branch }}
            - home-server-worker-dependencies-v2-{{ .Branch }}
            - home-server-worker-v2-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/home-server-base.tar | true
            docker load -i /caches/home-server-worker-dependencies.tar | true
            docker load -i /caches/home-server-worker.tar | true
      - run:
          name: Build worker dependencies Docker image
          command: |
            docker build \
              --cache-from=$DOCKER_USERNAME/home-server-worker-dependencies \
              -t "$DOCKER_USERNAME/home-server-worker-dependencies:$(echo $CIRCLE_SHA1 | head -c8)" \
              -t "$DOCKER_USERNAME/home-server-worker-dependencies:latest" \
              -f ./worker-dependencies.Dockerfile \
              .
      - run:
          name: Build worker Docker image
          command: |
            docker build \
              --cache-from=$DOCKER_USERNAME/home-server-worker \
              -t "$DOCKER_USERNAME/home-server-worker:$(echo $CIRCLE_SHA1 | head -c8)" \
              -t "$DOCKER_USERNAME/home-server-worker:latest" \
              -f ./worker.Dockerfile \
              .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin >/dev/null 2>&1
            docker push $DOCKER_USERNAME/home-server-worker-dependencies
            docker push $DOCKER_USERNAME/home-server-worker
          background: true
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/home-server-worker-dependencies.tar $DOCKER_USERNAME/home-server-worker-dependencies
            docker save -o /caches/home-server-worker.tar $DOCKER_USERNAME/home-server-worker
      - save_cache:
          key: home-server-worker-dependencies-v2-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/home-server-worker-dependencies.tar
      - save_cache:
          key: home-server-worker-v2-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/home-server-worker.tar
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: 'Update config files in ./kube with current container version'
          command: find ./kube/ -type f | xargs sed -i "s/CONTAINER_VERSION/$(echo $CIRCLE_SHA1 | head -c8)/g"
      - run:
          name: 'Creating cluster certificate from ENV'
          command: echo "$KUBERNETES_CLUSTER_CERTIFICATE" | base64 --decode > cert.crt
      - run:
          name: 'Apply Kubernetes config to server'
          command: |
            kubectl --kubeconfig=/dev/null \
              --certificate-authority=cert.crt \
              --server=$KUBERNETES_SERVER \
              --token=$KUBERNETES_SERVICE_ACC_TOKEN \
              apply -Rf ./kube/app/
      - run:
          name: 'Remove cluster certificate artifact'
          command: rm -f cert.crt
          when: always