---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-server-db-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      type: db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-server-redis-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      type: redis

---

