---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-server-app-deployment
  labels:
    cpcwood.com/name: home-server-app
    cpcwood.com/version: "1.0.0"
    cpcwood.com/component: application-server
    cpcwood.com/part-of: home-server
    cpcwood.com/managed-by: cpcwood
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: home-server-app
  template:
    metadata:
      labels:
        app: home-server-app
    spec:
      containers:
        - name: home-server-app
          image: cpcwood/home-server-app:CONTAINER_VERSION
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: home-server-app-config
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 2
            failureThreshold: 12
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]

---

apiVersion: v1
kind: Service
metadata:
  name: home-server-app-service
spec:
  selector:
    app: home-server-app
  ports:
    - name: http-proxy
      protocol: TCP
      port: 5000
      targetPort: 5000
