---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-server-worker-deployment
  labels:
    cpcwood.com/name: home-server-worker
    cpcwood.com/instance: home-server-worker
    cpcwood.com/version: '1.0.0'
    cpcwood.com/component: background-worker
    cpcwood.com/part-of: home-server
    cpcwood.com/managed-by: cpcwood
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 2
  selector:
    matchLabels:
      app: home-server-worker
  template:
    metadata:
      labels:
        app: home-server-worker
    spec:
      containers:
        - name: home-server-worker
          image: cpcwood/home-server-worker:CONTAINER_VERSION
          envFrom:
            - configMapRef:
                name: home-server-app-config
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ['./scripts/kube/sidekiq_quiet']
      terminationGracePeriodSeconds: 60

---

