default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.psql[:user] %>
  password: <%= Rails.application.credentials.psql[:password] %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.credentials.psql[:host] %>

development:
  <<: *default
  database: <%= Rails.application.credentials.psql[:dbname_development] %>

test:
  <<: *default
  database: <%= Rails.application.credentials.psql[:dbname_test] %>

production:
  <<: *default
  database: <%= Rails.application.credentials.psql[:dbname_production] %>