default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost

development:
  <<: *default
  database: home_server_development

test:
  <<: *default
  database: home_server_test

production:
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.psql[:user] %>
  password: <%= Rails.application.credentials.psql[:password] %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.credentials.psql[:host] %>
  database: <%= Rails.application.credentials.psql[:dbname_production] %>