default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD']  %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME_PRODUCTION') { 'home_server_production' } %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME_DEVELOPMENT') { 'home_server_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME_TEST') { 'home_server_test' } %>
