default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.psql[:user] %>
  password: <%= Rails.application.credentials.psql[:password] %>
  host: localhost

production:
  <<: *default
  pool: 5
  timeout: 5000
  host: <%= Rails.application.credentials.dig(:psql, :host) %>
  database: <%= Rails.application.credentials.dig(:psql, :dbname_production) || 'home_server_production' %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:psql, :dbname_development) || 'home_server_development' %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:psql, :dbname_test) || 'home_server_test' %>
