default: &default
  adapter: postgresql
  encoding: unicode
  database: home_server_<%= Rails.env %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD']  %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  pool: 5
  timeout: 5000

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
