resource "random_id" "application_storage_s3" {
  byte_length = 6
}

resource "aws_s3_bucket" "application_storage_s3" {
  bucket = "${var.application_storage_s3_bucket_name}-${var.environment}-${random_id.application_storage_s3.hex}"

  # Holds user uploads. A base-name change would force-replace (and CI holds
  # s3:DeleteBucket), so guard against accidental destruction.
  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket_public_access_block" "application_storage_s3" {
  bucket                  = aws_s3_bucket.application_storage_s3.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "application_storage_s3" {
  bucket = aws_s3_bucket.application_storage_s3.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "application_storage_s3" {
  bucket = aws_s3_bucket.application_storage_s3.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "application_storage_s3" {
  bucket = aws_s3_bucket.application_storage_s3.id

  rule {
    id     = "abort-incomplete-multipart-uploads"
    status = "Enabled"

    filter {}

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  rule {
    id     = "expire-noncurrent-versions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}

resource "aws_iam_user" "app_storage" {
  name = "home-server-app-storage-${var.environment}"
}

resource "aws_iam_user_policy" "app_storage" {
  name = "read-write-storage-bucket"
  user = aws_iam_user.app_storage.name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:PutObject",
          "s3:DeleteObject",
        ]
        Resource = "${aws_s3_bucket.application_storage_s3.arn}/*"
      },
      {
        Effect = "Allow"
        Action = [
          "s3:ListBucket",
          "s3:GetBucketLocation",
        ]
        Resource = aws_s3_bucket.application_storage_s3.arn
      },
    ]
  })
}

resource "aws_iam_access_key" "app_storage" {
  user = aws_iam_user.app_storage.name
}

# Bucket name carries a random suffix, so the app can't hardcode it — it is
# re-keyed into the app + worker secrets via ExternalSecret.
resource "aws_ssm_parameter" "app_storage" {
  name        = "${local.secret_prefix}/app-storage"
  description = "App S3 storage credentials + bucket name (generated by Terraform)"
  type        = "SecureString"
  value = jsonencode({
    AWS_ACCESS_KEY_ID     = aws_iam_access_key.app_storage.id
    AWS_SECRET_ACCESS_KEY = aws_iam_access_key.app_storage.secret
    AWS_BUCKET            = aws_s3_bucket.application_storage_s3.bucket
  })
}
