locals {
  secret_prefix      = "/${var.cluster}/home-server/${var.environment}"
  secret_placeholder = jsonencode({ placeholder = "set-by-populate-script" })
}

resource "aws_ssm_parameter" "app" {
  name        = "${local.secret_prefix}/app"
  description = "Rails / Sidekiq runtime secrets (SECRET_KEY_BASE, SMTP, Sentry, reCAPTCHA, AR encryption) — value set by scripts/populate-parameter-store.sh, not Terraform"
  type        = "SecureString"
  value       = local.secret_placeholder

  lifecycle {
    ignore_changes = [value]
  }
}

resource "random_password" "db" {
  length  = 32
  special = false
}

resource "aws_ssm_parameter" "db" {
  name        = "${local.secret_prefix}/db"
  description = "Postgres POSTGRES_USER and POSTGRES_PASSWORD (generated by Terraform)"
  type        = "SecureString"
  value = jsonencode({
    POSTGRES_USER     = "cpcwood"
    POSTGRES_PASSWORD = random_password.db.result
  })
}

resource "aws_ssm_parameter" "build" {
  name        = "${local.secret_prefix}/build"
  description = "Docker build-time secrets (MAX_MIND_LICENSE, GRECAPTCHA_SITE_KEY) — value set by scripts/populate-parameter-store.sh, not Terraform"
  type        = "SecureString"
  value       = local.secret_placeholder

  lifecycle {
    ignore_changes = [value]
  }
}
