resource "aws_ses_domain_identity" "email" {
  domain = var.email_domain
}

resource "aws_ses_domain_dkim" "email" {
  domain = aws_ses_domain_identity.email.domain
}

data "aws_iam_policy_document" "ses_send" {
  statement {
    effect    = "Allow"
    actions   = ["ses:SendRawEmail", "ses:SendEmail"]
    resources = [aws_ses_domain_identity.email.arn]
  }
}

resource "aws_iam_user" "ses_smtp" {
  name = "home-server-${var.environment}-ses-smtp"
}

resource "aws_iam_user_policy" "ses_smtp" {
  name   = "ses-send"
  user   = aws_iam_user.ses_smtp.name
  policy = data.aws_iam_policy_document.ses_send.json
}

resource "aws_iam_access_key" "ses_smtp" {
  user = aws_iam_user.ses_smtp.name
}

resource "aws_ssm_parameter" "email" {
  name        = "${local.secret_prefix}/email"
  description = "SES SMTP credentials (generated by Terraform)"
  type        = "SecureString"
  value = jsonencode({
    EMAIL_SMTP_USERNAME = aws_iam_access_key.ses_smtp.id
    EMAIL_SMTP_PASSWORD = aws_iam_access_key.ses_smtp.ses_smtp_password_v4
  })
}
