---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-server-db-volume
  labels:
    type: db
spec:
  capacity:
    storage: 1Gi
  storageClassName: ebs
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: <ebs-volume-id>
    fsType: ext4
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-server-redis-volume
  labels:
    type: redis
spec:
  capacity:
    storage: 1Gi
  storageClassName: ebs
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: <ebs-volume-id>
    fsType: ext4
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete

---