#!/usr/bin/env bash
# Sets the actual values for the Parameter Store entries that hold credentials
# issued by third parties — Rails app secrets (Sentry, SMTP, …) and the
# Docker build-time keys. Terraform creates these entries empty and ignores
# their value, so this script fills them in (and re-runs to rotate) without
# Terraform seeing a change.
#
# The db and app-storage credentials are generated by Terraform itself, so they
# are NOT set here — `terraform apply` writes them directly.
#
# Parameter naming: /<cluster>/home-server/<environment>/<bundle> — see
# infrastructure/terraform/secrets.tf.
#
# Requires AWS CLI v2 + jq, with credentials allowed to ssm:PutParameter /
# ssm:GetParameter on /<cluster>/home-server/<environment>/* plus kms:Decrypt
# via service=ssm.

set -euo pipefail

REGION="${AWS_REGION:-eu-west-2}"
PREFIX="${SSM_PREFIX:-/cpcwood-k8s/home-server/production}"

prompt() {
  local name="$1"
  local current="$2"
  if [[ -n "${current}" ]]; then
    printf '%s [keep existing]: ' "${name}" >&2
  else
    printf '%s: ' "${name}" >&2
  fi
  local value
  IFS= read -r value
  if [[ -z "${value}" && -n "${current}" ]]; then
    value="${current}"
  fi
  printf '%s' "${value}"
}

read_current() {
  aws ssm get-parameter \
    --region "${REGION}" \
    --name "$1" \
    --with-decryption \
    --query Parameter.Value \
    --output text 2>/dev/null || echo "{}"
}

put_parameter() {
  local name="$1"
  local payload="$2"
  aws ssm put-parameter \
    --region "${REGION}" \
    --name "${name}" \
    --type SecureString \
    --value "${payload}" \
    --overwrite >/dev/null
  echo "  ✓ updated ${name}"
}

populate_build() {
  echo "==> ${PREFIX}/build"
  local current
  current=$(read_current "${PREFIX}/build")
  local mml grck
  mml=$(prompt "MAX_MIND_LICENSE" "$(jq -r '.MAX_MIND_LICENSE // ""' <<<"${current}")")
  grck=$(prompt "GRECAPTCHA_SITE_KEY" "$(jq -r '.GRECAPTCHA_SITE_KEY // ""' <<<"${current}")")
  put_parameter "${PREFIX}/build" "$(jq -n --arg m "${mml}" --arg g "${grck}" '{MAX_MIND_LICENSE:$m, GRECAPTCHA_SITE_KEY:$g}')"
}

populate_app() {
  echo "==> ${PREFIX}/app"
  echo "  Provide every key. Press enter to keep the existing value."
  local current
  current=$(read_current "${PREFIX}/app")
  # Terraform-owned values are NOT here — the app's ExternalSecret re-keys
  # POSTGRES_USER/PASSWORD from <prefix>/db and the AWS storage creds + bucket
  # from <prefix>/app-storage.
  local keys=(
    ADMIN_EMAIL ADMIN_PASSWORD ADMIN_USERNAME
    AR_ENCRYPTION_DETERMINISTIC_KEY AR_ENCRYPTION_KEY_DERIVATION_SALT AR_ENCRYPTION_PRIMARY_KEY
    EMAIL_SMTP_PASSWORD EMAIL_SMTP_USERNAME
    GRECAPTCHA_SITE_KEY GRECAPTCHA_SITE_SECRET
    SECRET_KEY_BASE SENTRY_DSN
  )
  local payload="{}"
  for k in "${keys[@]}"; do
    local existing v
    existing=$(jq -r --arg k "$k" '.[$k] // ""' <<<"${current}")
    v=$(prompt "$k" "${existing}")
    payload=$(jq --arg k "$k" --arg v "$v" '. + {($k):$v}' <<<"${payload}")
  done
  put_parameter "${PREFIX}/app" "${payload}"
}

usage() {
  cat >&2 <<EOF
Usage: $0 [app|build|all]

Sets the values for the Parameter Store entries that hold third-party
credentials. The db and app-storage credentials are generated by Terraform
and are NOT managed here.

Override prefix with SSM_PREFIX env var (default: ${PREFIX}).
EOF
  exit 1
}

case "${1:-}" in
  app)    populate_app ;;
  build)  populate_build ;;
  all)    populate_build; populate_app ;;
  *)      usage ;;
esac
