version: "3.8"

services:
  app:
    tty: true
    stdin_open: true
    image: cpcwood/home-server-app-dev
    container_name: home-server-app-dev
    build:
      context: ../..
      dockerfile: .docker/dockerfiles/dev.Dockerfile
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      DB_USERNAME: cpcwood
      CHROMEDRIVER: /usr/bin/chromedriver
      GEM_PATH: /gems
      WEBPACKER_DEV_SERVER_HOST: "${DEV_SERVER_HOST:-0.0.0.0}"    
    env_file:
      - ../../config/env/.env
    volumes:
      - ../..:/opt/app/
      - data-home-server-dev-app-gems:/gems
      - ~/.bash_history:/root/.bash_history
    user: "${FIXUID:-1000}:${FIXGID:-1000}"
    depends_on:
      - postgres
      - redis
    command: './.docker/scripts/startup-app-dev'
    ports:
      - 5000:5000

  client:
    tty: true
    stdin_open: true
    image: cpcwood/home-server-client-dev
    container_name: home-server-client-dev
    build:
      context: ../..
      dockerfile: .docker/dockerfiles/dev.Dockerfile
    environment:
      GEM_PATH: /gems
      WEBPACKER_DEV_SERVER_PUBLIC: "${DEV_SERVER_HOST:-0.0.0.0}:3035"
    command: .docker/scripts/startup-client-dev
    entrypoint: .docker/scripts/entrypoint-dev
    env_file:
      - ../../config/env/.env
    depends_on:
      - app
    ports:
      - 3035:3035
    user: "${FIXUID:-1000}:${FIXGID:-1000}"
    volumes:
      - ../..:/opt/app/
      - data-home-server-dev-client-gems:/gems

  worker:
    image: cpcwood/home-server-worker-dev
    container_name: home-server-worker-dev
    build: 
      context: ../../
      dockerfile: .docker/dockerfiles/dev.Dockerfile
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      DB_USERNAME: cpcwood
      GEM_PATH: /gems
    env_file:
      - ../../config/env/.env
    volumes:
      - ../..:/opt/app/
      - data-home-server-dev-worker-gems:/gems
    user: "${FIXUID:-1000}:${FIXGID:-1000}"
    depends_on:
      - postgres
      - redis
      - app
    command: './.docker/scripts/startup-worker-dev'
    security_opt:
      - seccomp:"./.docker/config/chrome.json"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: cpcwood
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432
    volumes:
      - data-home-server-dev-postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U cpcwood -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:5-alpine
    command: redis-server
    volumes:
      - data-home-server-dev-redis:/data
    ports: 
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  data-home-server-dev-postgres:
  data-home-server-dev-redis:
  data-home-server-dev-app-gems:
  data-home-server-dev-client-gems:
  data-home-server-dev-worker-gems:
