version: "3.7"

services:
  app:
    stdin_open: true
    tty: true
    image: home-server-app-dev
    build: 
      context: ../..
      dockerfile: .docker/dockerfiles/dev.Dockerfile
    container_name: home-server-app-dev
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      DB_USERNAME: cpcwood
      CHROMEDRIVER: /usr/bin/chromedriver
    env_file:
      - ../../config/env/.env
    volumes:
      - ../..:/opt/app/
    depends_on:
      - postgres
      - redis
    command: './.docker/scripts/startup-app.dev.sh'
    ports:
      - 5000:5000

  worker:
    image: home-server-worker-dev
    build: 
      context: ../../
      dockerfile: .docker/dockerfiles/dev.Dockerfile
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      DB_USERNAME: cpcwood
    env_file:
      - ../../config/env/.env
    volumes:
      - ../..:/opt/app/
    depends_on:
      - postgres
      - redis
      - app
    container_name: home-server-worker-dev
    command: './.docker/scripts/startup-worker.dev.sh'
    security_opt:
      - seccomp:"./config/chrome.json"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: cpcwood
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432
    volumes:
      - data-home-server-dev-postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U cpcwood -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:5-alpine
    command: redis-server
    volumes:
      - data-home-server-dev-redis:/data
    ports: 
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  data-home-server-dev-postgres:
  data-home-server-dev-redis: