version: "3.7"

services:
  app:
    stdin_open: true
    tty: true
    image: home-server-app-dev
    build: 
      context: ../..
      dockerfile: .docker/dockerfiles/dev.Dockerfile
    container_name: home-server-app-test
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      DB_USERNAME: cpcwood
      DB_PASSWORD: password
      DB_PORT: 5433
      PGPORT: 5433
      CHROMEDRIVER: /usr/bin/chromedriver
    env_file:
      - ../../config/env/test-defaults.env
    volumes:
      - ../..:/opt/app/
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: cpcwood
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: 5433
    volumes:
      - data-home-server-test-postgres:/var/lib/postgresql/data
    ports:
      - 5433:5433
    healthcheck:
      test: pg_isready -U cpcwood -h 127.0.0.1
      interval: 5s

volumes:
  data-home-server-test-postgres: